# Generated by Django 4.2.7 on 2023-11-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_date_of_birth_alter_profile_first_name_and_more'),
        ('main', '0002_rename_group_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Book title')),
                ('author', models.CharField(max_length=70, verbose_name='Author')),
                ('genre', models.CharField(blank=True, max_length=70, null=True, verbose_name='Genre')),
                ('synopsis', models.TextField(blank=True, max_length=500, null=True, verbose_name='Synopsis')),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.AddField(
            model_name='roommembers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rooms'),
        ),
        migrations.AddField(
            model_name='roommembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='books',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.rooms'),
        ),
    ]
